DOMAIN = "gmc300"
FRIENDLY_NAME = "GMC-300E"
MANUFACTORER = "GQ"
SUGGESTED_AREA = "corridor"

DEFAULT_PORT = "/dev/ttyUSB-geiger"
DEFAULT_BAUD_RATE = 115200
DEFAULT_DEVICE_TYPE = None
DEFAULT_VERBOSE_LEVEL = 2

CONF_PERSISTENT_CONNECTION = "persistent_connection"

DEFAULT_SCAN_INTERVAL = 5
DEFAULT_PERSISTENT_CONNECTION = True

DATA_CONNECTION = "connection"
DATA_CANCEL = "cancel"
DATA_WORKING = "working"
DATA_DEVICE_INFO = "device_info"

DISPATCHER_UPDATE = "update"


